//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.12 at 11:41:55 AM COT 
//


package aerolineas_latinoamericanas.contract.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for domain-events-info complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="domain-events-info">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alert-on-air">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="alert-type" type="{http://aerolineas-latinoamericanas/contract/messages}alert-type"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="on-air-shopping">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="credit-card-number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="transaction-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="actual-outgate">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="actual-ingate">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="estimated-outgate">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="estimated-ingate">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cancel-flight">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "domain-events-info", propOrder = {
    "alertOnAir",
    "onAirShopping",
    "actualOutgate",
    "actualIngate",
    "estimatedOutgate",
    "estimatedIngate",
    "cancelFlight"
})
public class DomainEventsInfo {

    @XmlElement(name = "alert-on-air", required = true)
    protected AlertOnAir alertOnAir;
    @XmlElement(name = "on-air-shopping", required = true)
    protected OnAirShopping onAirShopping;
    @XmlElement(name = "actual-outgate", required = true)
    protected ActualOutgate actualOutgate;
    @XmlElement(name = "actual-ingate", required = true)
    protected ActualIngate actualIngate;
    @XmlElement(name = "estimated-outgate", required = true)
    protected EstimatedOutgate estimatedOutgate;
    @XmlElement(name = "estimated-ingate", required = true)
    protected EstimatedIngate estimatedIngate;
    @XmlElement(name = "cancel-flight", required = true)
    protected CancelFlight cancelFlight;

    /**
     * Gets the value of the alertOnAir property.
     * 
     * @return
     *     possible object is
     *     {@link AlertOnAir }
     *     
     */
    public AlertOnAir getAlertOnAir() {
        return alertOnAir;
    }

    /**
     * Sets the value of the alertOnAir property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertOnAir }
     *     
     */
    public void setAlertOnAir(AlertOnAir value) {
        this.alertOnAir = value;
    }

    /**
     * Gets the value of the onAirShopping property.
     * 
     * @return
     *     possible object is
     *     {@link OnAirShopping }
     *     
     */
    public OnAirShopping getOnAirShopping() {
        return onAirShopping;
    }

    /**
     * Sets the value of the onAirShopping property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnAirShopping }
     *     
     */
    public void setOnAirShopping(OnAirShopping value) {
        this.onAirShopping = value;
    }

    /**
     * Gets the value of the actualOutgate property.
     * 
     * @return
     *     possible object is
     *     {@link ActualOutgate }
     *     
     */
    public ActualOutgate getActualOutgate() {
        return actualOutgate;
    }

    /**
     * Sets the value of the actualOutgate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualOutgate }
     *     
     */
    public void setActualOutgate(ActualOutgate value) {
        this.actualOutgate = value;
    }

    /**
     * Gets the value of the actualIngate property.
     * 
     * @return
     *     possible object is
     *     {@link ActualIngate }
     *     
     */
    public ActualIngate getActualIngate() {
        return actualIngate;
    }

    /**
     * Sets the value of the actualIngate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualIngate }
     *     
     */
    public void setActualIngate(ActualIngate value) {
        this.actualIngate = value;
    }

    /**
     * Gets the value of the estimatedOutgate property.
     * 
     * @return
     *     possible object is
     *     {@link EstimatedOutgate }
     *     
     */
    public EstimatedOutgate getEstimatedOutgate() {
        return estimatedOutgate;
    }

    /**
     * Sets the value of the estimatedOutgate property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstimatedOutgate }
     *     
     */
    public void setEstimatedOutgate(EstimatedOutgate value) {
        this.estimatedOutgate = value;
    }

    /**
     * Gets the value of the estimatedIngate property.
     * 
     * @return
     *     possible object is
     *     {@link EstimatedIngate }
     *     
     */
    public EstimatedIngate getEstimatedIngate() {
        return estimatedIngate;
    }

    /**
     * Sets the value of the estimatedIngate property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstimatedIngate }
     *     
     */
    public void setEstimatedIngate(EstimatedIngate value) {
        this.estimatedIngate = value;
    }

    /**
     * Gets the value of the cancelFlight property.
     * 
     * @return
     *     possible object is
     *     {@link CancelFlight }
     *     
     */
    public CancelFlight getCancelFlight() {
        return cancelFlight;
    }

    /**
     * Sets the value of the cancelFlight property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancelFlight }
     *     
     */
    public void setCancelFlight(CancelFlight value) {
        this.cancelFlight = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "date",
        "gateCode",
        "fuelPercentage"
    })
    public static class ActualIngate {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "gate-code", required = true)
        protected String gateCode;
        @XmlElement(name = "fuel-percentage")
        protected int fuelPercentage;

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the gateCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGateCode() {
            return gateCode;
        }

        /**
         * Sets the value of the gateCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGateCode(String value) {
            this.gateCode = value;
        }

        /**
         * Gets the value of the fuelPercentage property.
         * 
         */
        public int getFuelPercentage() {
            return fuelPercentage;
        }

        /**
         * Sets the value of the fuelPercentage property.
         * 
         */
        public void setFuelPercentage(int value) {
            this.fuelPercentage = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "date",
        "gateCode",
        "fuelPercentage"
    })
    public static class ActualOutgate {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "gate-code", required = true)
        protected String gateCode;
        @XmlElement(name = "fuel-percentage")
        protected int fuelPercentage;

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the gateCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGateCode() {
            return gateCode;
        }

        /**
         * Sets the value of the gateCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGateCode(String value) {
            this.gateCode = value;
        }

        /**
         * Gets the value of the fuelPercentage property.
         * 
         */
        public int getFuelPercentage() {
            return fuelPercentage;
        }

        /**
         * Sets the value of the fuelPercentage property.
         * 
         */
        public void setFuelPercentage(int value) {
            this.fuelPercentage = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="alert-type" type="{http://aerolineas-latinoamericanas/contract/messages}alert-type"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "alertType"
    })
    public static class AlertOnAir {

        @XmlElement(required = true)
        protected String description;
        @XmlElement(name = "alert-type", required = true)
        @XmlSchemaType(name = "string")
        protected AlertType alertType;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the alertType property.
         * 
         * @return
         *     possible object is
         *     {@link AlertType }
         *     
         */
        public AlertType getAlertType() {
            return alertType;
        }

        /**
         * Sets the value of the alertType property.
         * 
         * @param value
         *     allowed object is
         *     {@link AlertType }
         *     
         */
        public void setAlertType(AlertType value) {
            this.alertType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description"
    })
    public static class CancelFlight {

        @XmlElement(required = true)
        protected String description;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "date",
        "gateCode",
        "fuelPercentage"
    })
    public static class EstimatedIngate {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "gate-code", required = true)
        protected String gateCode;
        @XmlElement(name = "fuel-percentage")
        protected int fuelPercentage;

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the gateCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGateCode() {
            return gateCode;
        }

        /**
         * Sets the value of the gateCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGateCode(String value) {
            this.gateCode = value;
        }

        /**
         * Gets the value of the fuelPercentage property.
         * 
         */
        public int getFuelPercentage() {
            return fuelPercentage;
        }

        /**
         * Sets the value of the fuelPercentage property.
         * 
         */
        public void setFuelPercentage(int value) {
            this.fuelPercentage = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="gate-code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fuel-percentage" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "date",
        "gateCode",
        "fuelPercentage"
    })
    public static class EstimatedOutgate {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "gate-code", required = true)
        protected String gateCode;
        @XmlElement(name = "fuel-percentage")
        protected int fuelPercentage;

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the gateCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGateCode() {
            return gateCode;
        }

        /**
         * Sets the value of the gateCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGateCode(String value) {
            this.gateCode = value;
        }

        /**
         * Gets the value of the fuelPercentage property.
         * 
         */
        public int getFuelPercentage() {
            return fuelPercentage;
        }

        /**
         * Sets the value of the fuelPercentage property.
         * 
         */
        public void setFuelPercentage(int value) {
            this.fuelPercentage = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="credit-card-number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="transaction-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "creditCardNumber",
        "value",
        "transactionDate"
    })
    public static class OnAirShopping {

        @XmlElement(required = true)
        protected String description;
        @XmlElement(name = "credit-card-number", required = true)
        protected String creditCardNumber;
        protected long value;
        @XmlElement(name = "transaction-date", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar transactionDate;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the creditCardNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreditCardNumber() {
            return creditCardNumber;
        }

        /**
         * Sets the value of the creditCardNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreditCardNumber(String value) {
            this.creditCardNumber = value;
        }

        /**
         * Gets the value of the value property.
         * 
         */
        public long getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(long value) {
            this.value = value;
        }

        /**
         * Gets the value of the transactionDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTransactionDate() {
            return transactionDate;
        }

        /**
         * Sets the value of the transactionDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTransactionDate(XMLGregorianCalendar value) {
            this.transactionDate = value;
        }

    }

}
