//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.12 at 11:41:55 AM COT 
//


package aerolineas_latinoamericanas.contract.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flight-leg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="flight-leg">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="operational-info" type="{http://aerolineas-latinoamericanas/contract/messages}operational-info"/>
 *         &lt;element name="scheduled-info" type="{http://aerolineas-latinoamericanas/contract/messages}scheduled-info"/>
 *         &lt;element name="domain-events-info" type="{http://aerolineas-latinoamericanas/contract/messages}domain-events-info"/>
 *       &lt;/sequence>
 *       &lt;attribute name="external-key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" type="{http://aerolineas-latinoamericanas/contract/messages}flight-status" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flight-leg", propOrder = {
    "operationalInfo",
    "scheduledInfo",
    "domainEventsInfo"
})
public class FlightLeg {

    @XmlElement(name = "operational-info", required = true)
    protected OperationalInfo operationalInfo;
    @XmlElement(name = "scheduled-info", required = true)
    protected ScheduledInfo scheduledInfo;
    @XmlElement(name = "domain-events-info", required = true)
    protected DomainEventsInfo domainEventsInfo;
    @XmlAttribute(name = "external-key")
    protected String externalKey;
    @XmlAttribute(name = "status")
    protected FlightStatus status;
    @XmlAttribute(name = "version")
    protected Integer version;

    /**
     * Gets the value of the operationalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link OperationalInfo }
     *     
     */
    public OperationalInfo getOperationalInfo() {
        return operationalInfo;
    }

    /**
     * Sets the value of the operationalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalInfo }
     *     
     */
    public void setOperationalInfo(OperationalInfo value) {
        this.operationalInfo = value;
    }

    /**
     * Gets the value of the scheduledInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduledInfo }
     *     
     */
    public ScheduledInfo getScheduledInfo() {
        return scheduledInfo;
    }

    /**
     * Sets the value of the scheduledInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduledInfo }
     *     
     */
    public void setScheduledInfo(ScheduledInfo value) {
        this.scheduledInfo = value;
    }

    /**
     * Gets the value of the domainEventsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DomainEventsInfo }
     *     
     */
    public DomainEventsInfo getDomainEventsInfo() {
        return domainEventsInfo;
    }

    /**
     * Sets the value of the domainEventsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainEventsInfo }
     *     
     */
    public void setDomainEventsInfo(DomainEventsInfo value) {
        this.domainEventsInfo = value;
    }

    /**
     * Gets the value of the externalKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalKey() {
        return externalKey;
    }

    /**
     * Sets the value of the externalKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalKey(String value) {
        this.externalKey = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link FlightStatus }
     *     
     */
    public FlightStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightStatus }
     *     
     */
    public void setStatus(FlightStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersion(Integer value) {
        this.version = value;
    }

}
